'use client'
import { useEffect, useState } from 'react'

type AppScreenshotSlotProps = { label: string }
const metrics = [{label:'PAGINA’S LIVE',target:806,prefix:'',suffix:'',note:'+ 12 deze week'}, {label:'ZOEKMACHINE + AI VERKEER',target:92,prefix:'+',suffix:'%',note:'en stijgend'}, {label:'AI-VERMELDINGEN',target:420,prefix:'',suffix:'',note:'+ 38 deze maand'}]
const pages=[['Gids: complete tuin aanleggen met bestrating','GEPUBLICEERD'],['Warmtepomp of hybride warmtepomp vergelijken','VERBETERD'],['Wat kost een nieuwe cv-ketel inclusief montage?','GEPUBLICEERD']]

export default function AppScreenshotSlot({ label }: AppScreenshotSlotProps) {
 const [progress,setProgress]=useState(0)
 useEffect(()=>{const start=performance.now();const id=requestAnimationFrame(function frame(now){const p=Math.min((now-start)/1800,1);setProgress(1-Math.pow(1-p,3));if(p<1)requestAnimationFrame(frame)});return()=>cancelAnimationFrame(id)},[])
 return <figure className="app-shot"><div className="mac-window"><div className="mac-window__bar"><span className="mac-dot mac-dot--red"/><span className="mac-dot mac-dot--yellow"/><span className="mac-dot mac-dot--green"/><span className="mac-window__title">ORBIT ENGINE</span><span className="preview-live">● ALWAYS ON</span></div><div className="growth-preview"><aside className="growth-sidebar"><p className="preview-logo">ORBIT ENGINE</p><div className="preview-company">▦ &nbsp; JOUWDOMEIN.NL <b>⌄</b></div><p className="is-active">⌂ &nbsp; Resultaten</p><p>⌁ &nbsp; Zichtbaarheid</p><p>▤ &nbsp; Pagina&apos;s</p><small>STRATEGIE</small><p>□ &nbsp; Contentplan</p><p>◌ &nbsp; Openstaande vragen</p><p>▤ &nbsp; Bibliotheek</p><small>MIJN BEDRIJF</small><p>◉ &nbsp; Merk­dossier</p></aside><section className="growth-main"><p className="preview-eyebrow">RESULTATEN</p><h3>Gegenereerde groei met ORBIT ENGINE</h3><p className="growth-subtitle">JOUWDOMEIN.NL <b>·</b> ALWAYS ON</p><div className="growth-metrics">{metrics.map(metric=><div className="growth-metric" key={metric.label}><small>{metric.label}</small><strong>{metric.prefix}{Math.round(metric.target*progress).toLocaleString('nl-NL')}{metric.suffix}</strong><span>↗ &nbsp;{metric.note}</span></div>)}</div><div className="growth-chart"><p>ORGANISCH + AI ZICHTBAARHEID, DIT KWARTAAL</p><svg viewBox="0 0 760 180" preserveAspectRatio="none" aria-label="Stijgende zichtbaarheidsgrafiek"><defs><linearGradient id="growth-fill" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#bcff2f" stopOpacity=".24"/><stop offset="1" stopColor="#bcff2f" stopOpacity="0"/></linearGradient></defs><path className="chart-grid" d="M0 35H760M0 90H760M0 145H760"/><path className="chart-area" d="M0 150 C32 122 45 134 72 112 S110 129 142 100 S190 105 214 83 S252 115 280 77 S325 78 350 66 S390 71 420 45 S468 56 500 38 S538 43 565 26 S617 32 648 19 S690 27 720 8 S744 12 760 0 V180 H0Z"/><path className="chart-line" d="M0 150 C32 122 45 134 72 112 S110 129 142 100 S190 105 214 83 S252 115 280 77 S325 78 350 66 S390 71 420 45 S468 56 500 38 S538 43 565 26 S617 32 648 19 S690 27 720 8 S744 12 760 0"/></svg></div><div className="publishing-head"><span>GEPUBLICEERDE PAGINA&apos;S</span><b>Deze maand · 7 pagina&apos;s</b></div><div className="published-pages">{pages.map(([title,status],index)=><div className="published-page" key={title}><i>▤</i><div><strong>{title}</strong><span><em style={{width:`${80-index*13}%`}}/> </span></div><b>{status==='GEPUBLICEERD'?'✓ ': '↗ '}{status}</b></div>)}</div></section></div><div className="app-shot__fade"/></div><figcaption>SCREENSHOT — {label}</figcaption></figure>
}
