import DeGeslotenLusDiagram from './diagrams/DeGeslotenLusDiagram'
import KlantreisVragenDiagram from './diagrams/KlantreisVragenDiagram'
import PaginaTypenDiagram from './diagrams/PaginaTypenDiagram'
import KennislaagDiagram from './diagrams/KennislaagDiagram'
import SchrijfEnControleDiagram from './diagrams/SchrijfEnControleDiagram'
import EffectMetingDiagram from './diagrams/EffectMetingDiagram'
import AppScreenshotSlot from './AppScreenshotSlot'
import ComparisonTable from './ComparisonTable'

export default function ArticleBody(){return <article id="artikel" className="article-copy mx-auto max-w-3xl px-5 py-16 sm:py-24">
<p className="kicker mb-10">ORBIT ENGINE · ARTIKEL VOOR DE WEBSITE · CONCEPT VOOR DE COPYWRITER</p>
<p>Stel je een klant voor die vanavond zijn laptop openklapt en typt: “welk installatiebedrijf in Eindhoven kan mijn cv-ketel vervangen, en wat kost dat ongeveer?”. Hij scrolt niet door tien blauwe links. Hij krijgt één antwoord, met daarin drie of vier bedrijven. Staat jouw bedrijf daar niet tussen, dan heb je die klant verloren voordat hij ooit op je website kwam. Je weet niet eens dat hij bestond.</p>
<p>Dat is de nieuwe werkelijkheid van gevonden worden. En het is precies het probleem waarvoor ik ORBIT ENGINE heb gebouwd.</p>
<h2>Drie problemen die elke ondernemer herkent</h2>
<h3>1. Zoeken is verhuisd van de zoekmachine naar de chatbot</h3><p>Jarenlang was de vraag: sta ik op pagina één van Google? Die vraag verschuift. Steeds meer mensen stellen hun vraag aan ChatGPT, of lezen het AI-antwoord dat Google bovenaan de resultaten zet. Die assistent kiest zelf welke bedrijven hij noemt, en waarom. Zichtbaar zijn in die antwoorden heet GEO: Generative Engine Optimization. Het is de opvolger van SEO, met andere spelregels.</p><p>Een AI-assistent zoekt geen zoekwoorden, hij zoekt het beste, meest concrete antwoord. Wie dat antwoord op zijn website heeft staan, wordt genoemd. Wie dat niet heeft, bestaat niet. Het lastige: de meeste bedrijven hebben geen idee of ze genoemd worden. Er is geen positie 3 om naar te kijken, alleen een antwoord dat bij elke vraag anders is.</p>
<h3>2. Goede content schrijven kost onevenredig veel tijd</h3><p>Het antwoord op GEO is inhoud: pagina&apos;s die de vragen van je klanten echt beantwoorden. Maar wie ooit een goede dienstpagina heeft laten maken, weet wat dat kost. Een briefing schrijven. Een copywriter inwerken in je vak. Wachten op een eerste versie. Feedbackrondes, omdat de tekst net niet klinkt als jouw bedrijf. Na een paar weken en een paar honderd euro heb je één pagina. En je hebt er misschien veertig nodig.</p>
<h3>3. En wie het door AI laat schrijven, krijgt algemene brij</h3><p>Dus doen veel bedrijven het logische: ze laten ChatGPT de tekst schrijven. Het resultaat kennen we allemaal. Vlot, foutloos, en volkomen inwisselbaar. “Bij ons staat de klant centraal.” “Wij leveren maatwerk van hoge kwaliteit.” Een tekst die elke concurrent ook had kunnen publiceren, omdat hij niets bevat wat alleen jij weet.</p><p>Erger nog: een taalmodel dat iets niet weet, vult het graag zelf in. Een garantie die je niet geeft. Een prijs die niet klopt. Een keurmerk dat je niet hebt. En hier zit de ironie: een AI-assistent die antwoorden samenstelt, heeft precies aan zo&apos;n algemene tekst niets. Hij zoekt de bron met concrete kennis. Algemene AI-tekst maakt je dus niet zichtbaarder in AI. Hij maakt je onzichtbaarder.</p>
<h2 id="werking">Het antwoord: een lus, geen losse tool</h2><p>De meeste tools lossen één stukje op. Een monitoringtool laat zien dat je niet genoemd wordt, en daar houdt het op. Een schrijftool schrijft over het onderwerp dat jij opgeeft, zonder te weten of dat onderwerp ertoe doet.</p><p>ORBIT ENGINE doet het anders. Het doorloopt de hele cyclus, en begint na de laatste stap gewoon opnieuw: kansen ontdekken, meten wat AI-assistenten nu over jouw markt zeggen, bepalen welke pagina&apos;s ontbreken, de kennis ophalen die alleen jij hebt, schrijven, controleren, en na publicatie opnieuw meten om te zien of het gewerkt heeft. Elke ronde maakt de volgende scherper.</p>
<DeGeslotenLusDiagram /><p>Het uitgangspunt waarop alles rust: ORBIT ENGINE probeert niet de mooiste AI-tekst te maken, maar de kennis van de ondernemer zo goed mogelijk bij een uitstekende AI-schrijver te krijgen. Dat verschil klinkt klein. In de praktijk is het het verschil tussen een tekst die je negeert en een pagina die een AI-assistent aanhaalt.</p>
<h2>Stap 1: ontdekken wie je bent, en wat AI al over je denkt</h2><p>Het begint met een webadres. ORBIT ENGINE bekijkt tot duizend pagina&apos;s van je site en leest er tot honderdvijftig helemaal. Daaruit bouwt het een aanbodboom: al je diensten en producten, netjes geordend. Met een harde regel: elke dienst moet te bewijzen zijn met een citaat dat letterlijk op je eigen site staat. De app controleert elk citaat. Een dienst zonder bewijs valt af. Zo neemt het systeem nooit per ongeluk het aanbod van een concurrent over.</p><p>Daarna volgt de kennistest. ORBIT ENGINE vraagt aan AI wat die over jouw bedrijf weet, en vergelijkt het antwoord met de feiten van je eigen site. Klopt je werkgebied? Je aanbod? Word je verward met een gelijknamig bedrijf? “ChatGPT denkt dat je in Eindhoven zit, terwijl je in Tilburg zit” is voor veel ondernemers de meest onthutsende uitkomst van het hele traject. Tegelijk kijkt de app of AI-bedrijven je site wel mogen bezoeken, want een verkeerd ingestelde website sluit ze soms zonder dat iemand het weet buiten.</p>
<AppScreenshotSlot label="ORBIT ENGINE · Kennislaag interface" />
<h2>Stap 2: clusters, en meten wat kopers echt vragen</h2><p>Een ondernemer denkt in diensten. Een klant denkt in problemen. ORBIT ENGINE vertaalt het ene naar het andere met clusters: onderwerpen zoals een koper ze zoekt. Niet te breed (“fysiotherapie”), niet te smal (“dry needling bij frozen shoulder”), maar precies zoals iemand met een probleem het vraagt (“hardloopblessure behandelen”).</p><p>Per cluster stelt ORBIT ENGINE dertig vragen op die kopers werkelijk aan een AI-assistent stellen, verdeeld over de hele klantreis: tien van iemand die zich net oriënteert, tien van iemand die opties vergelijkt, en tien van iemand die op het punt staat te kiezen. Werk je lokaal, dan krijgt elke vraag een plaats uit je werkgebied. En nooit staat je eigen merknaam in een vraag, of die van een concurrent. Want de vraag is niet of AI je kent als je naar je vraagt. De vraag is of AI je uit zichzelf aanbeveelt.</p>
<KlantreisVragenDiagram /><p>Pas als de vragen zijn goedgekeurd, wordt er gemeten. Dan stelt ORBIT ENGINE ze aan het model achter ChatGPT, met zoeken op internet aan, zoals een gewone gebruiker dat doet, en kijkt ook mee in het AI-antwoord van Google. De zwaarste vragen worden drie keer gesteld, omdat één antwoord toeval kan zijn. Per antwoord legt de app vast of je genoemd wordt, op welke plek, in welke rol, en wie er in jouw plaats genoemd wordt.</p><p>En, het mooiste deel: waarom die concurrent genoemd wordt, met een letterlijk citaat uit het antwoord als bewijs. Alles komt samen in één zichtbaarheidsscore, mét een marge die zegt hoe zeker die score is. Geen schijnprecisie. Een vraag waarbij AI helemaal geen bedrijf noemt, telt apart en niet als verlies.</p>
<AppScreenshotSlot label="Live meting in ChatGPT & Google AI" rows={3}/>
<h2>Stap 3: van gemis naar kans, en de juiste soort pagina</h2><p>Cijfers zonder besluit zijn een dashboard. ORBIT ENGINE zet de meting om in kansen: concrete pagina&apos;s die nodig zijn om de vragen te winnen die je nu verliest. Elke kans staat op bewijs uit de meting en zegt precies wat de pagina moet doen: welke gemiste vragen hij moet winnen, voor wie hij is, wat de ene kernvraag is die hij beantwoordt, en of het een nieuwe pagina wordt of een bestaande die beter moet.</p><p>De app legt daarvoor je aanbodboom naast je bestaande pagina&apos;s, en ziet dus waar een dienst geen pagina heeft of een zwakke. En er geldt: één kans, één pagina. Wijst een nieuwe meting opnieuw naar een onderwerp dat al een kans heeft, dan wordt dat extra bewijs bij die kans, in plaats van een tweede pagina die met de eerste gaat concurreren.</p>
<PaginaTypenDiagram /><p>Bij een artikel, gids, vergelijking of pagina met veelgestelde vragen kijkt het onderzoek bovendien naar wat Google nu op die vraag laat zien, inclusief de vragen die mensen daar ook stellen. Alles komt in een contentplan van twaalf maanden, waarin de kansen met de meeste potentie vooraan staan.</p>
<h2>De kennislaag: het geheugen van je bedrijf</h2><p>Hier zit het hart van ORBIT ENGINE, en het grootste verschil met elke AI-schrijftool. Alles wat het systeem over je bedrijf weet, staat op één plek: de kennislaag. Je aanbod, je feiten, je prijzen en termijnen, je verhalen uit de praktijk, je manier van praten, en wat juist niet gezegd mag worden. Elk stukje kennis draagt zijn herkomst mee.</p><p>Staat het letterlijk op je site en is het citaat teruggevonden? Dan heet het waargenomen. Heb jij het verteld, of stond het in een brochure die je hebt toegevoegd? Dan is het verklaard. Is het een vermoeden van de AI? Dan is het afgeleid, en dan gaat het niet mee naar de schrijver. Nooit.</p>
<KennislaagDiagram /><p>Zeggen twee bronnen iets anders over hetzelfde, bijvoorbeeld twee verschillende prijzen voor dezelfde dienst, dan gaat geen van beide naar de schrijver totdat duidelijk is welke klopt. Het principe daarachter loopt door het hele systeem: onbekend is beter dan fout. Een pagina zonder prijs is jammer. Een pagina met een verkeerde prijs is schadelijk.</p><p>Het mooie is dat de kennislaag groeit. Elk antwoord dat je geeft, elk document dat je toevoegt, elk verhaal dat je vertelt, wordt herbruikbaar. Geldt een antwoord voor je hele bedrijf, dan gaat het automatisch mee naar elke volgende pagina. Je vertelt het één keer.</p>
<h2>De vragen die alleen jij kunt beantwoorden</h2><p>Dit is het moment dat ORBIT ENGINE het meest onderscheidt, en het is geen bijzaak maar de kern van het product. Voordat er één woord geschreven wordt, maakt de app per pagina een content brief. Met zoeken op internet zoekt de AI uit wat een bezoeker over dit onderwerp wil weten, welke vakkennis erbij hoort, altijd met de bron erbij, en wat klanten vaak verkeerd begrijpen.</p><p>Daarna legt de app dat naast alles wat de kennislaag al weet, en stelt de vraag die geen gewone AI-tool stelt: wat ontbreekt er nog om deze pagina echt goed en volledig te maken?</p><p>Het resultaat zijn hooguit acht gerichte vragen aan jou, de ondernemer. Over concrete feiten, over een klus die je laatst deed, over hoe je werkt, over de twijfels die klanten hebben en wat jij dan zegt. Alleen vragen waarvan het antwoord echt in de tekst terechtkomt en die niet al bekend zijn. Nul vragen is ook een goed antwoord. Bovenaan staat steeds dezelfde open vraag: “Wat wil je zelf op deze pagina vertellen?”</p><ul className="mb-6 list-square pl-5"><li>De pagina&apos;s van een maand worden na elkaar voorbereid. Zo krijgt je nooit vijf keer dezelfde vraag in andere woorden.</li><li>Is een eerder antwoord ook nuttig voor deze pagina, dan krijgt de schrijver dat antwoord gewoon mee.</li><li>Er is geen knop “schrijf nu”. Jouw laatste antwoord is de startknop.</li></ul><p>Een halve minuut werk voor de app, een paar minuten voor jou. Precies die paar minuten maken van een inwisselbare tekst een pagina die alleen van jou kan zijn.</p>
<h2>Schrijven en controleren: de lat van een vakcopywriter</h2><p>Pas als alle vragen beantwoord zijn, schrijft het sterkste AI-model dat ORBIT ENGINE gebruikt de pagina. Het krijgt alles mee: de zoekintentie, de vragen die gewonnen moeten worden, de zekere kennis over je bedrijf, jouw antwoorden letterlijk, het onderzoek, de rol van deze pagina naast de andere pagina&apos;s in hetzelfde cluster, en voorbeelden van hoe jouw bedrijf klinkt. Met de opdracht de toon over te nemen, niet de zinnen.</p><p>Wat het bewust niet meekrijgt: een aantal woorden, een verplicht stramien, een lijst punten die erin moet. Dat is precies wat AI-teksten star en voorspelbaar maakt. De pagina is zo lang als nodig is, en niet langer.</p><p>Daarna begint de controle, in twee lagen.</p><ul className="mb-6 list-square pl-5"><li><strong>Harde feiten worden in code gecontroleerd.</strong> Elk bedrag, elk getal met een eenheid, elk jaartal, elk woord als “garantie”, “gecertificeerd”, “24/7” of “de beste” wordt teruggezocht in wat de schrijver aan kennis meekreeg.</li><li><strong>Een tweede model leest mee als eindredacteur.</strong> Het beantwoordt twee vragen: klopt het, en is het goed? Wordt de vraag meteen beantwoord, klinkt het als dit bedrijf, heeft de lezer er iets aan?</li></ul>
<SchrijfEnControleDiagram /><p>Is het oordeel “niet goed”, dan wordt de pagina één keer herschreven met concrete verbeterpunten. Wat daarna nog twijfel oproept, beslist de app niet zelf: die zinnen worden geel gemarkeerd, en jij bevestigt of past ze aan voordat de pagina goedgekeurd kan worden. Jij houdt de laatste klik.</p><p>Na goedkeuring krijg je een compleet publicatiepakket: de tekst als HTML, platte tekst of Markdown, een titel en omschrijving voor zoekmachines op de juiste lengte, veelgestelde vragen, de gestructureerde gegevens die zoekmachines en AI-assistenten helpen de pagina te begrijpen, een voorgesteld webadres, voorstellen voor interne links, en als de app je websitesysteem herkent een versie die daar direct in past, bijvoorbeeld voor WordPress.</p>
<h2>En dan het belangrijkste: bewijzen dat het werkt</h2><p>Hier stoppen andere tools. Hier begint ORBIT ENGINE pas echt. Een score die stijgt na publicatie bewijst op zich niets. Zichtbaarheid in AI beweegt ook vanzelf. Wie dan roept “het werkt”, gokt. Daarom werkt ORBIT ENGINE zoals een goed opgezet experiment.</p><p>Zodra je doorgeeft dat een pagina live staat, controleert de app eerst of hij er echt staat, met de juiste tekst en de juiste gegevens voor zoekmachines. Daarna plant hij twee hermetingen, na 14 en na 28 dagen. Dan meet hij twee groepen naast elkaar: de vragen waarvoor de pagina gemaakt is, en een controlegroep van vragen uit hetzelfde cluster waarvoor geen pagina gemaakt is. Stijgt alles even hard, dan lag het niet aan de pagina. Stijgen alleen de doelvragen, dan is dat bewijs.</p>
<EffectMetingDiagram /><p>Het oordeel is streng: gestegen, gelijk of gedaald. Valt het verschil binnen de marge, dan is het “gelijk”. Zijn er te weinig gegevens, dan zegt de app dat, in plaats van een mooi verhaal te vertellen. Daarnaast kijkt ORBIT ENGINE of de AI jouw nieuwe pagina zelf als bron aanhaalt, en met een koppeling met Google Search Console zie je ook vertoningen en klikken per pagina.</p><p>En dan begint de lus opnieuw. Elke maand meet ORBIT ENGINE alle clusters opnieuw, controleert de techniek van je site, vindt nieuwe gaten, en zet nieuwe kansen in het plan.</p>
<h2>Wat dit betekent voor je tijd en je budget</h2><p>Laten we het concreet maken. Een goede, onderbouwde pagina laten schrijven door een copywriter kost al snel een paar honderd euro en een paar weken doorlooptijd, als je de briefing en de feedbackrondes meerekent. Voor een merk dat veertig pagina&apos;s nodig heeft, is dat een investering waar de meeste mkb-bedrijven nooit aan beginnen.</p><p>ORBIT ENGINE bereidt een pagina in een halve minuut voor en schrijft hem in ongeveer een minuut. De rekenkosten van het complete traject voor één pagina, van onderzoek en vragen tot schrijven, controleren en herschrijven, blijven onder de twintig dollarcent. De enige tijd die jij erin steekt, is die paar minuten om de vragen te beantwoorden, en het lezen en goedkeuren. Precies de stukken waarin jouw kennis onmisbaar is.</p>
<ComparisonTable />
<h2>Voor ondernemers, en voor marketingbureaus</h2><p>Als ondernemer krijg je iets wat je voorheen alleen met een compleet team had: iemand die bijhoudt of AI je noemt, weet welke pagina&apos;s er ontbreken, de juiste vragen stelt, schrijft in jouw stem, en daarna eerlijk laat zien wat het opleverde. Je hoeft geen SEO-specialist te zijn, en geen copywriter aan te sturen.</p><p>Als marketingbureau is ORBIT ENGINE een manier om GEO als dienst aan te bieden zonder dat je team evenredig mee hoeft te groeien. Elk merk heeft zijn eigen kennislaag, eigen clusters, eigen meting en eigen contentplan, allemaal in één omgeving. De vragen aan de klant vervangen het eindeloze heen en weer van briefings: de kennis gaat van je klant rechtstreeks naar de schrijver. En elke pagina heeft een meetbaar resultaat met controlegroep. Dat is een rapportage waar je klant iets aan heeft, en een reden om te blijven.</p>
<h2>Wat er verder onder de motorkap zit</h2><ul className="mb-6 list-square pl-5"><li><strong>Waarom wint de concurrent?</strong> Per concurrent haalt de app uit de AI-antwoorden waarom die genoemd wordt, met citaten als bewijs.</li><li><strong>Mijn reputatie.</strong> Wat zeggen AI-assistenten over je bedrijf? Toon, pluspunten, minpunten en reviewcijfers, waarbij de app die cijfers zelf op de bronpagina controleert.</li><li><strong>Externe bronnen.</strong> Welke vergelijkers, reviewplatforms en vakbladen haalt AI in jouw markt aan, en sta jij daar tussen?</li><li><strong>Technische controle, elke maand.</strong> Mogen AI-bedrijven je site lezen, en staan de gegevens voor zoekmachines erop?</li><li><strong>Kennis toevoegen.</strong> Een brochure, een tarievenlijst of een offertetekst toevoegen, met dezelfde strenge controle.</li><li><strong>Alles is na te gaan.</strong> Elk antwoord van elk AI-model wordt volledig bewaard.</li></ul>
<h2 id="slot">Tot slot</h2><p>Ik heb ORBIT ENGINE niet gebouwd omdat de wereld nog een AI-schrijftool nodig had. Die zijn er genoeg, en ze maken het probleem vooral groter. Ik heb het gebouwd omdat gevonden worden in AI uit veel stappen bestaat, die pas waarde hebben als ze op elkaar aansluiten: ontdekken wat er ontbreekt, de kennis ophalen die alleen de ondernemer heeft, schrijven op het niveau van een vakcopywriter, elke harde bewering controleren, en eerlijk meten wat het oplevert.</p><p>Het resultaat is een systeem dat niet alleen content maakt, maar zichtbaarheid opbouwt. Ronde na ronde, maand na maand.</p><blockquote>Benieuwd wat ChatGPT vandaag over jouw bedrijf zegt? Dat is precies waar we beginnen.</blockquote>
</article>}
