const pillars=[['01','Zie wat AI zegt','Meet koopvragen in ChatGPT en Google AI. Zie wie genoemd wordt, waarom, en met welk citaat als bewijs.'],['02','Kies de juiste pagina','Zet gemeten gemis om in één concrete kans: de juiste pagina, voor de juiste lezer, op het juiste moment.'],['03','Schrijf met bewezen kennis','De kennislaag geeft de schrijver alleen feiten die op je site staan of door jou zijn verteld.'],['04','Bewijs wat verandert','Meet doelvragen naast een controlegroep. Niet gokken of een pagina werkt, maar het eerlijk vaststellen.']]
export default function ProductPage(){return <>
<section className="social-proof"><div><span className="section-label">HET BEWIJS</span><p>Merken die we onmogelijk te negeren maakten</p></div><div className="client-logos" aria-label="Merken die ORBIT ENGINE gebruiken"><span className="logo-porsche">PORSCHE</span><span className="logo-volkswagen"><b>VW</b><em>VOLKSWAGEN</em></span><span className="logo-audi"><b>○○○○</b><em>AUDI</em></span><span className="logo-bentley"><b>— B —</b><em>BENTLEY</em></span><span className="logo-cupra"><b>◇</b><em>CUPRA</em></span></div></section>
<section className="section problem"><div className="section-label">HET PROBLEEM</div><div><h2>Gevonden worden is veranderd.</h2><p className="lead">Je klant zoekt niet meer alleen in Google. Die vraagt ChatGPT of Google AI om een antwoord. Wie daar niet wordt genoemd, bestaat op dat moment niet.</p></div><div className="problem-cards"><article><b>01</b><h3>Onzichtbaar in AI</h3><p>Je weet niet of jouw bedrijf genoemd wordt wanneer iemand om een aanbeveling vraagt.</p></article><article><b>02</b><h3>Content zonder richting</h3><p>Losse AI-tools schrijven zonder te weten welke pagina je nodig hebt om te winnen.</p></article><article><b>03</b><h3>Geen bewijs van groei</h3><p>Een stijgende score zegt niets zonder een goede controlegroep.</p></article></div></section>
<section id="werking" className="section cycle"><div className="section-label">ÉÉN SYSTEEM</div><div className="cycle-heading"><h2>Elke stap verbonden.</h2><p>ORBIT ENGINE vervangt losse tools door een lus die steeds slimmer wordt.</p></div><div className="cycle-grid">{pillars.map(([number,title,text])=><article key={number}><span>{number}</span><h3>{title}</h3><p>{text}</p><i>→</i></article>)}</div></section>
<section className="section feature feature--reverse"><div className="feature-copy"><div className="section-label">DE KENNISLAAG</div><h2>Onbekend is beter dan fout.</h2><p>Alles wat ORBIT ENGINE over je bedrijf weet, heeft een herkomst. Waargenomen op je site, door jou verklaard, of afgewezen als vermoeden van AI.</p><a href="mailto:hello@outerorbit.nl?subject=Demo%20aanvragen">Bekijk de kennislaag →</a></div><div className="knowledge-card"><small>KENNISLAAG / JOUWDOMEIN.NL</small><div><b>✓</b><span>Werkgebied: Eindhoven en omgeving</span><em>WAARGENOMEN</em></div><div><b>✓</b><span>24/7 spoedhulp voor cv-ketels</span><em>VERKLAARD</em></div><div className="dim"><b>×</b><span>Landelijke dekking</span><em>AFGELEID</em></div><footer>Alleen bewezen kennis bereikt de schrijver.</footer></div></section>
<section className="section feature"><div className="effect-card"><small>RESULTAATMETING / 28 DAGEN</small><div className="effect-columns"><p><b>+18%</b><span>Doelvragen</span></p><p><b>+2%</b><span>Controlegroep</span></p></div><div className="effect-line"><i/><i/><i/><i/><i/></div><strong>OORDEEL: GESTEGEN</strong></div><div className="feature-copy"><div className="section-label">BEWIJS, GEEN BELOFTE</div><h2>Zie wat je werk werkelijk oplevert.</h2><p>Na publicatie meet ORBIT ENGINE opnieuw. Doelvragen naast een controlegroep, na 14 en 28 dagen. Zo zie je wat veranderde en wat toeval was.</p><a href="mailto:hello@outerorbit.nl?subject=Demo%20aanvragen">Bekijk hoe de meting werkt →</a></div></section>
<section className="section audience"><div className="section-label">VOOR WIE</div><h2>Een GEO-systeem dat met je meegroeit.</h2><div><article><span>VOOR ONDERNEMERS</span><h3>Een compleet team, zonder een compleet team.</h3><p>Weet wat AI over je zegt, welke pagina&apos;s ontbreken en waar je tijd het meeste oplevert.</p><a href="mailto:hello@outerorbit.nl?subject=Demo%20aanvragen">Demo aanvragen →</a></article><article><span>VOOR BUREAUS</span><h3>Maak GEO een schaalbare dienst.</h3><p>Geef ieder merk zijn eigen kennislaag, meting en contentplan zonder eindeloze briefings.</p><a href="mailto:hello@outerorbit.nl?subject=Demo%20aanvragen">Praat met ons →</a></article></div></section>
<section className="final-cta"><p className="kicker">BEGIN MET ZIEN WAT ER NU GEBEURT</p><h2>Benieuwd wat AI vandaag over jouw bedrijf zegt?</h2><a href="mailto:hello@outerorbit.nl?subject=Demo%20aanvragen">Demo aanvragen <span>↗</span></a></section>
</>}
