const GoogleMark=()=> <span className="source-logo source-logo--google" aria-label="Google">G</span>
const ChatGPTMark=()=> <span className="source-logo source-logo--chatgpt" aria-label="ChatGPT">✺</span>

const marketCards=[
  ['WEBWINKEL · HARDLOOPSCHOENEN','DOEL · MEER ONLINE VERKOOP','“beste hardloopschoenen”','215.000'],
  ['LOKALE DIENST · HOVENIER','DOEL · GEBELD WORDEN','“tuin laten aanleggen”','144.000'],
  ['B2B · MKB-VERZEKERING','DOEL · GEKWALIFICEERDE LEADS','“zakelijke aansprakelijkheidsverzekering”','41.000'],
]
const steps=[
  ['01','Merkintelligentie','ORBIT leert eerst je bedrijf kennen.'],
  ['02','Strategie & kansanalyse','Kansen worden vertaald naar een gericht contentplan.'],
  ['03','Creatie','Content ontstaat vanuit bewezen bedrijfskennis.'],
  ['04','Geautomatiseerd publiceren','Goedgekeurde pagina’s gaan zelfstandig live.'],
  ['05','Continu optimaliseren','Resultaten sturen iedere volgende ronde aan.'],
  ['06','Meetbare groei','Google- en AI-zichtbaarheid worden eerlijk gemeten.'],
]

export default function ProductPage(){return <>
  <section className="social-proof"><div><span className="section-label">HET BEWIJS</span><p>Merken die we onmogelijk te negeren maakten</p></div><div className="client-logos" aria-label="Merken die ORBIT ENGINE gebruiken"><span className="logo-porsche">PORSCHE</span><span className="logo-volkswagen"><b>VW</b><em>VOLKSWAGEN</em></span><span className="logo-audi"><b>○○○○</b><em>AUDI</em></span><span className="logo-bentley"><b>— B —</b><em>BENTLEY</em></span><span className="logo-cupra"><b>◇</b><em>CUPRA</em></span></div></section>

  <section className="home-section search-shift"><div className="section-label">HET PROBLEEM · DE NIEUWE REALITEIT</div><h2>Zoeken is veranderd. Niet genoemd worden <span>kost klanten.</span></h2><p className="section-intro">Zoeken was jarenlang een lijst met links. Nu geven Google en AI-platforms direct antwoord. ORBIT zorgt dat jouw merk onderdeel wordt van dat antwoord.</p><div className="search-compare"><article><header><GoogleMark/><b>Google</b><small>DRAAIT OM POSITIES &amp; LINKS</small></header><div className="search-query"><GoogleMark/><strong>beste partner voor mijn bedrijf</strong><i>⌕</i></div>{[1,2,3,4].map(number=><div className="result-row" key={number}><b>{number}</b><div><i/><span/><span/></div></div>)}</article><div className="compare-arrow">→</div><article><header><ChatGPTMark/><b>ChatGPT</b><small>DRAAIT OM GENOEMD EN AANBEVOLEN WORDEN</small></header><div className="chat-question">Welke partner past het beste bij mijn organisatie?</div><div className="answer-row"><ChatGPTMark/><div><i/><span/><span/><span/></div></div><div className="chat-question chat-question--right">En waar kan ik die het beste vinden?</div><div className="answer-row"><ChatGPTMark/><div><i/><span/><span/></div></div></article></div></section>

  <section className="home-section markets"><div className="section-label">ELKE MARKT · ELKE NICHE</div><h2>ORBIT vindt vragen die jouw klanten <span>vandaag al stellen.</span></h2><p className="section-intro">Echte vragen, uit verschillende markten. ORBIT ontdekt waar vraag bestaat en waar jouw merk nog niet het antwoord is.</p><div className="market-grid">{marketCards.map(([label,goal,query,volume])=><article key={label}><div className="market-icon">⌁</div><h3>{label}</h3><small>{goal}</small><p>{query}</p><strong>{volume}</strong><em>ZOEKOPDRACHTEN / MND<br/>ALLEEN AL DEZE ZOEKOPDRACHT</em><footer>+ 3 VERWANTE VRAGEN</footer></article>)}</div><p className="section-footnote">ELKE MARKT HEEFT ER DUIZENDEN ZOALS DEZE. ORBIT VINDT ZE ALLEMAAL, OOK DIE VAN JOU.</p></section>

  <section id="werking" className="home-section how-it-works"><div className="section-label">HOE HET WERKT</div><h2>Van jouw bedrijfskennis naar zichtbaar resultaat. <span>Volledig verbonden.</span></h2><div className="workflow"><div className="workflow-steps">{steps.map(([number,title,copy],index)=><article className={index===0?'is-open':''} key={number}><b>{number}</b><div><h3>{title}</h3>{index===0&&<><small>ORBIT LEERT JOUW BEDRIJF EERST KENNEN</small><p>{copy} Het onderzoekt je merk, aanbod, tone of voice, klanten en concurrenten, zodat alles herkenbaar van jou blijft.</p></>}</div></article>)}</div><div className="workflow-visual"><header><i/><i/><i/><b>ORBIT ENGINE</b><span>● AUTONOOM · ALWAYS ON</span></header><div className="engine-core"><div className="core-orbit"><span>ORBIT</span></div><aside className="engine-card card--voice"><b>⌁ Tone of voice</b><i>▮▯▮▮▯▮▯</i></aside><aside className="engine-card card--audience"><b>♙ Doelgroepen</b><i>● &nbsp; ● &nbsp; ●</i></aside><aside className="engine-card card--product"><b>▦ Producten &amp; diensten</b><i>□ &nbsp; □ &nbsp; □</i></aside><aside className="engine-card card--journey"><b>⌘ Klantreis</b><i>● · · ● · ●</i></aside><aside className="engine-card card--competition"><b>◎ Concurrenten</b><i>A &nbsp; B &nbsp; C</i></aside></div></div></div></section>

  <section className="home-section autonomy"><div className="autonomy-copy"><div className="section-label">AUTONOOM AI-PLATFORM + MENSELIJKE EXPERTISE</div><h2>ORBIT werkt volledig autonoom. Onze experts houden het <span>menselijk.</span></h2><div className="split-stat"><strong>100%</strong><div><h3>Autonome software</h3><p>ORBIT draait de hele motor: onderzoek, strategie, content, publicatie, optimalisatie en meting. Geen uren boeken. Het systeem werkt 24/7.</p></div></div><div className="human-row"><div className="avatar-stack"><i>OA</i><i>AI</i><i>CS</i><b>+20</b></div><div><h3>Echte mensen als hulp</h3><p>Je krijgt deskundige begeleiding van strategen en contentspecialisten. Autonoom waar het kan, menselijk waar dat waarde toevoegt.</p></div></div></div><div className="system-orbit"><span className="system-core">ORBIT</span><i>ONDERZOEK</i><i>STRATEGIE</i><i>CONTENT</i><i>METING</i></div></section>

  <section className="closing-cta"><p className="section-label">GEEN TIJD VOOR SEO? MOOI.</p><h2>Klaar voor <span>autonome groei?</span></h2><p>Zie wat er verborgen zit in je Google- en AI-zichtbaarheid. Jij bepaalt de koers; ORBIT onderzoekt, creëert, publiceert en optimaliseert continu.</p><div><a href="mailto:hello@outerorbit.nl?subject=Gratis%20demo%20plannen">Plan een gratis demo ↗</a><a href="#top">Bekijk de resultaten →</a></div></section>
</>}
