const GoogleMark=()=> <span className="source-logo source-logo--google" role="img" aria-label="Google"><b>G</b></span>
const ChatGPTMark=()=> <span className="source-logo source-logo--chatgpt" role="img" aria-label="ChatGPT"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3.1a4.45 4.45 0 0 1 7.6 3.15 4.46 4.46 0 0 1 1.08 8.08 4.45 4.45 0 0 1-6.52 5.52 4.46 4.46 0 0 1-7.84-2.58A4.45 4.45 0 0 1 4.4 9.72 4.46 4.46 0 0 1 12 3.1Zm0 3.05-4.96 2.86v5.73L12 17.6l4.96-2.86V9.01L12 6.15Zm0 2.07 3.17 1.83v3.66L12 15.54l-3.17-1.83v-3.66L12 8.22Z"/></svg></span>
const SearchIcon=()=> <svg className="search-icon" viewBox="0 0 20 20" aria-hidden="true"><circle cx="8.5" cy="8.5" r="4.5"/><path d="m12 12 4 4"/></svg>
const TransitionArrow=()=> <svg className="transition-arrow" viewBox="0 0 44 28" aria-hidden="true"><path d="M2 14h36M28 4l10 10-10 10"/></svg>
const GoogleResult=({number,width}:{number:number;width:number})=><div className="google-result"><b>{number}</b><div><i style={{width:`${width}%`}}/><span style={{width:'91%'}}/><span style={{width:`${48+number*4}%`}}/></div><em>↗</em></div>
const AiResponse=({width=78}:{width?:number})=><div className="ai-response"><ChatGPTMark/><div><i style={{width:`${width}%`}}/><span/><span/><span className="short"/></div><em>●</em></div>

const marketCards=[
  ['WEBWINKEL · HARDLOOPSCHOENEN','DOEL · MEER ONLINE VERKOOP','“beste hardloopschoenen”','215.000'],
  ['LOKALE DIENST · HOVENIER','DOEL · GEBELD WORDEN','“tuin laten aanleggen”','144.000'],
  ['B2B · MKB-VERZEKERING','DOEL · GEKWALIFICEERDE LEADS','“zakelijke aansprakelijkheidsverzekering”','41.000'],
]
const steps=[
  ['01','Merkintelligentie','ORBIT leert eerst je bedrijf kennen.'],
  ['02','Strategie & kansanalyse','Kansen worden vertaald naar een gericht contentplan.'],
  ['03','Creatie','Content ontstaat vanuit bewezen bedrijfskennis.'],
  ['04','Geautomatiseerd publiceren','Goedgekeurde pagina’s gaan zelfstandig live.'],
  ['05','Continu optimaliseren','Resultaten sturen iedere volgende ronde aan.'],
  ['06','Meetbare groei','Google- en AI-zichtbaarheid worden eerlijk gemeten.'],
]

export default function ProductPage(){return <>
  <section className="social-proof"><div><span className="section-label">HET BEWIJS</span><p>Merken die we onmogelijk te negeren maakten</p></div><div className="client-logos" aria-label="Merken die ORBIT ENGINE gebruiken"><span className="logo-porsche">PORSCHE</span><span className="logo-volkswagen"><b>VW</b><em>VOLKSWAGEN</em></span><span className="logo-audi"><b>○○○○</b><em>AUDI</em></span><span className="logo-bentley"><b>— B —</b><em>BENTLEY</em></span><span className="logo-cupra"><b>◇</b><em>CUPRA</em></span></div></section>

  <section className="home-section search-shift"><div className="section-label">HET PROBLEEM · DE NIEUWE REALITEIT</div><h2>Zoeken is veranderd. Niet genoemd worden <span>kost klanten.</span></h2><p className="section-intro">Zoeken was jarenlang een lijst met links. Nu geven Google en AI-platforms direct antwoord. ORBIT zorgt dat jouw merk onderdeel wordt van dat antwoord.</p><div className="search-compare"><div className="situation-column"><div className="situation-heading"><strong>Oude situatie</strong><span>Ranken met zoekwoorden</span></div><article className="search-panel search-panel--google"><header><div><GoogleMark/><b>Google</b></div><small>POSITIES &amp; LINKS</small></header><div className="search-query"><GoogleMark/><strong>beste partner voor mijn bedrijf</strong><SearchIcon/></div><div className="google-results"><GoogleResult number={1} width={72}/><GoogleResult number={2} width={66}/><GoogleResult number={3} width={78}/><GoogleResult number={4} width={61}/><GoogleResult number={5} width={69}/></div><footer><span>G</span><span>b</span><span>Y!</span><b>DRAAIT OM POSITIES &amp; LINKS</b></footer></article></div><div className="compare-arrow"><TransitionArrow/></div><div className="situation-column"><div className="situation-heading"><strong>Nieuwe situatie</strong><span>Het relevante antwoord zijn</span></div><article className="search-panel search-panel--chat"><header><div><ChatGPTMark/><b>ChatGPT</b></div><small>GENOEMD &amp; AANBEVOLEN</small></header><div className="chat-thread"><div className="chat-question">Welke partner past het beste bij mijn organisatie?<span>J</span></div><AiResponse width={74}/><div className="chat-question chat-question--right">Welke expertise hebben zij precies?<span>J</span></div><AiResponse width={83}/><div className="chat-question chat-question--right">En waar kan ik contact opnemen?<span>J</span></div></div><footer><div><ChatGPTMark/><span>✦</span><span>◎</span><span>◈</span></div><b>DRAAIT OM GENOEMD &amp; AANBEVOLEN WORDEN</b></footer></article></div></div></section>

  <section className="home-section markets"><div className="section-label">ELKE MARKT · ELKE NICHE</div><h2>ORBIT vindt vragen die jouw klanten <span>vandaag al stellen.</span></h2><p className="section-intro">Echte vragen, uit verschillende markten. ORBIT ontdekt waar vraag bestaat en waar jouw merk nog niet het antwoord is.</p><div className="market-grid">{marketCards.map(([label,goal,query,volume])=><article key={label}><div className="market-icon">⌁</div><h3>{label}</h3><small>{goal}</small><p>{query}</p><strong>{volume}</strong><em>ZOEKOPDRACHTEN / MND<br/>ALLEEN AL DEZE ZOEKOPDRACHT</em><footer>+ 3 VERWANTE VRAGEN</footer></article>)}</div><p className="section-footnote">ELKE MARKT HEEFT ER DUIZENDEN ZOALS DEZE. ORBIT VINDT ZE ALLEMAAL, OOK DIE VAN JOU.</p></section>

  <section id="werking" className="home-section how-it-works"><div className="section-label">HOE HET WERKT</div><h2>Van jouw bedrijfskennis naar zichtbaar resultaat. <span>Volledig verbonden.</span></h2><div className="workflow"><div className="workflow-steps">{steps.map(([number,title,copy],index)=><article className={index===0?'is-open':''} key={number}><b>{number}</b><div><h3>{title}</h3>{index===0&&<><small>ORBIT LEERT JOUW BEDRIJF EERST KENNEN</small><p>{copy} Het onderzoekt je merk, aanbod, tone of voice, klanten en concurrenten, zodat alles herkenbaar van jou blijft.</p></>}</div></article>)}</div><div className="workflow-visual"><header><i/><i/><i/><b>ORBIT ENGINE</b><span>● AUTONOOM · ALWAYS ON</span></header><div className="engine-core"><div className="core-orbit"><span>ORBIT</span></div><aside className="engine-card card--voice"><b>⌁ Tone of voice</b><i>▮▯▮▮▯▮▯</i></aside><aside className="engine-card card--audience"><b>♙ Doelgroepen</b><i>● &nbsp; ● &nbsp; ●</i></aside><aside className="engine-card card--product"><b>▦ Producten &amp; diensten</b><i>□ &nbsp; □ &nbsp; □</i></aside><aside className="engine-card card--journey"><b>⌘ Klantreis</b><i>● · · ● · ●</i></aside><aside className="engine-card card--competition"><b>◎ Concurrenten</b><i>A &nbsp; B &nbsp; C</i></aside></div></div></div></section>

  <section className="home-section autonomy"><div className="autonomy-copy"><div className="section-label">AUTONOOM AI-PLATFORM + MENSELIJKE EXPERTISE</div><h2>ORBIT werkt volledig autonoom. Onze experts houden het <span>menselijk.</span></h2><div className="split-stat"><strong>100%</strong><div><h3>Autonome software</h3><p>ORBIT draait de hele motor: onderzoek, strategie, content, publicatie, optimalisatie en meting. Geen uren boeken. Het systeem werkt 24/7.</p></div></div><div className="human-row"><div className="avatar-stack"><i>OA</i><i>AI</i><i>CS</i><b>+20</b></div><div><h3>Echte mensen als hulp</h3><p>Je krijgt deskundige begeleiding van strategen en contentspecialisten. Autonoom waar het kan, menselijk waar dat waarde toevoegt.</p></div></div></div><div className="system-orbit"><span className="system-core">ORBIT</span><i>ONDERZOEK</i><i>STRATEGIE</i><i>CONTENT</i><i>METING</i></div></section>

  <section className="closing-cta"><p className="section-label">GEEN TIJD VOOR SEO? MOOI.</p><h2>Klaar voor <span>autonome groei?</span></h2><p>Zie wat er verborgen zit in je Google- en AI-zichtbaarheid. Jij bepaalt de koers; ORBIT onderzoekt, creëert, publiceert en optimaliseert continu.</p><div><a href="mailto:hello@outerorbit.nl?subject=Gratis%20demo%20plannen">Plan een gratis demo ↗</a><a href="#top">Bekijk de resultaten →</a></div></section>
</>}
