'use client'

import { useState } from 'react'
import { ArrowRight, Check, MagnifyingGlass as Search, Sparkle as Sparkles, User as UserRound, Robot as Bot, ChartLineUp as ChartNoAxesCombined, ShieldCheck, CheckCircle as CircleCheck, ChatText as MessageSquareText } from '@phosphor-icons/react'
import './homepage.css'

const contact = 'mailto:hello@outerorbit.nl?subject=Kennismaken%20met%20ORBIT%20ENGINE'

const stages = [
  { label: 'Kans gevonden', icon: Search },
  { label: 'Voorstel gemaakt', icon: Sparkles },
  { label: 'Jouw akkoord', icon: CircleCheck },
  { label: 'Effect volgen', icon: ChartNoAxesCombined },
]

function ProductDemo() {
  const [active, setActive] = useState(0)
  return <div className="product-demo" aria-label="Interactief voorbeeld van de ORBIT ENGINE werkwijze">
    <div className="demo-top"><span className="demo-wordmark">◒ &nbsp; ORBIT ENGINE</span><span><i /> Software actief</span></div>
    <div className="demo-layout">
      <nav className="demo-steps" aria-label="Stappen in het proces">
        {stages.map(({ label, icon: Icon }, index) => <button key={label} onClick={() => setActive(index)} className={active === index ? 'active' : ''} aria-pressed={active === index}><Icon size={18}/><span><small>0{index + 1}</small>{label}</span></button>)}
      </nav>
      <div className="demo-canvas">
        <div className="demo-meta"><span>VOORBEELDDOSSIER</span><b>De Groene Dakdekker · Utrecht</b><em>Voorbeelddata</em></div>
        {active === 0 && <div className="demo-screen opportunity"><p className="screen-label">Nieuwe klantvraag</p><h3>“Wat kost een sedumdak op een uitbouw?”</h3><div className="signal-row"><div><Search/><span>Zoekvraag gevonden</span><b>Concrete koopintentie</b></div><ArrowRight/><div><Sparkles/><span>Kans voor verbetering</span><b>Bestaande dienstenpagina mist antwoord</b></div></div><p className="demo-note">ORBIT koppelt klantvragen aan je aanbod en bestaande website, en zet de duidelijkste kansen vooraan.</p></div>}
        {active === 1 && <div className="demo-screen proposal"><p className="screen-label">Contentvoorstel</p><h3>Kosten van een sedumdak op een uitbouw</h3><div className="brief-grid"><span>DOELGROEP<b>Huiseigenaren</b></span><span>WERKGEBIED<b>Regio Utrecht</b></span><span>PAGINATYPE<b>Dienstenpagina</b></span></div><div className="copy-preview"><b>Een groendak voor jouw uitbouw</b><p>Voor woningen in regio Utrecht adviseren we een lichtgewicht sedumsysteem. We beoordelen eerst de dakconstructie en afwatering, zodat het voorstel past bij jouw woning.</p><mark>Gebaseerd op 4 bevestigde bedrijfsfeiten</mark></div></div>}
        {active === 2 && <div className="demo-screen approval"><p className="screen-label">Eén belangrijk beslismoment</p><h3>Klaar voor jouw beoordeling</h3><div className="review-card"><ShieldCheck size={28}/><div><b>Feiten gecontroleerd</b><p>Werkgebied, werkwijze en diensten sluiten aan op het bedrijfsdossier.</p></div></div><div className="review-card"><MessageSquareText size={28}/><div><b>1 vraag voor jou</b><p>Geldt de constructiecheck voor ieder type uitbouw?</p></div></div><div className="fake-actions"><button>Terug voor aanpassing</button><button><Check/> Goedkeuren</button></div></div>}
        {active === 3 && <div className="demo-screen tracking"><p className="screen-label">Zichtbaarheid volgen</p><h3>Dezelfde klantvraag, doorlopend gemeten</h3><div className="track-cards"><div><span>Google</span><b>Pagina geïndexeerd</b><small>Laatste controle: vandaag</small></div><div><span>AI-antwoorden</span><b>Bronvermelding volgen</b><small>Vragen uit dit onderwerp</small></div></div><div className="line-chart" aria-label="Illustratieve meetlijn"><i/><i/><i/><i/><i/><i/><svg viewBox="0 0 500 90" preserveAspectRatio="none"><path d="M0 74 C70 70 90 65 145 66 S210 50 260 54 S330 37 370 40 S440 20 500 12"/></svg></div><small className="demo-disclaimer">Illustratieve weergave — geen resultaatclaim.</small></div>}
      </div>
    </div>
  </div>
}

export default function Homepage() {
  return <div className="homepage">
    <section className="new-hero" id="top"><div className="hero-grid"><div className="hero-copy"><p className="overline"><span/> Software die doorwerkt. Een adviseur die meedenkt.</p><h1>Beter gevonden in <em>Google én AI.</em><br/>Zonder nóg een tool te beheren.</h1><p className="lede">ORBIT ENGINE onderzoekt kansen, maakt en verbetert content en volgt wat dat doet met je zichtbaarheid. Jij houdt invloed op belangrijke keuzes; een vast aanspreekpunt begeleidt de aanpak.</p><div className="primary-actions"><a className="primary-button" href={contact}>Plan een kennismaking <ArrowRight/></a><a className="text-link" href="#werking">Bekijk hoe het werkt <span>↓</span></a></div><div className="human-note"><span><UserRound/></span><p><b>Persoonlijk begeleid</b> — samen brengen we je bedrijf, doelen en prioriteiten scherp in beeld.</p></div></div><div className="hero-demo"><ProductDemo/></div></div></section>

    <section className="channel-section"><div className="section-head"><p className="overline">Eén koopbehoefte, twee routes</p><h2>Je klant zoekt niet op één plek.</h2><p>ORBIT ENGINE werkt aan vindbare, bruikbare antwoorden — voor klassieke zoekresultaten én antwoorden van AI-assistenten.</p></div><div className="channels"><article><div className="channel-title"><span className="google-g">G</span><div><small>ILLUSTRATIEF VOORBEELD</small><b>Zoeken in Google</b></div></div><div className="query"><Search/> sedumdak uitbouw kosten utrecht</div><div className="search-result"><small>degroenedakdekker.nl › sedumdak-uitbouw</small><b>Een sedumdak op je uitbouw: opties en aandachtspunten</b><p>Bekijk wat de dakconstructie, afwatering en oppervlakte betekenen voor een passend voorstel…</p></div></article><article><div className="channel-title"><span className="ai-icon"><Bot/></span><div><small>ILLUSTRATIEF VOORBEELD</small><b>Vragen aan een AI-assistent</b></div></div><div className="query"><MessageSquareText/> Waar moet ik op letten bij een sedumdak?</div><div className="ai-answer"><Sparkles/><p>Let onder meer op de draagkracht, afwatering en het gewicht van het gekozen systeem. Een lokale specialist kan de constructie vooraf beoordelen.</p></div></article></div></section>

    <section className="knowledge-section" id="werking"><div className="knowledge-copy"><p className="overline">Bedrijfskennis als basis</p><h2>Geen algemene AI-tekst. Wel jouw werkelijkheid.</h2><p>ORBIT verzamelt bevestigde informatie over je aanbod, doelgroep en werkwijze. Die kennislaag — het Brand Intelligence Brain — voedt ieder voorstel en voorkomt dat de software zomaar details invult.</p><ul><li><Check/> Eén keer bevestigen, daarna herbruikbaar</li><li><Check/> Onzekerheden blijven zichtbaar voor beoordeling</li><li><Check/> Content sluit aan op je echte dienstverlening</li></ul></div><div className="knowledge-flow"><div className="fact-stack"><span><small>WERKGEBIED</small><b>Utrecht + 30 km</b><i>Bevestigd</i></span><span><small>WERKWIJZE</small><b>Constructiecheck vooraf</b><i>Bevestigd</i></span><span><small>DOELGROEP</small><b>Particuliere woningeigenaren</b><i>Bevestigd</i></span></div><ArrowRight className="flow-arrow-new"/><div className="output-card"><small>CONCEPTFRAGMENT</small><p>“Voor woningen in <mark>regio Utrecht</mark> beoordelen we vooraf de <mark>dakconstructie en afwatering</mark>. Zo weet je welk sedumsysteem past bij jouw uitbouw.”</p><footer><ShieldCheck/> 3 bevestigde feiten toegepast</footer></div></div></section>

    <section className="collab-section"><div className="section-head"><p className="overline">Zo werken we samen</p><h2>Veel uitvoering. Weinig bediening.</h2><p>Geen nieuw dashboard dat je dagelijks moet bijhouden. De software doet het terugkerende werk; je adviseur bewaakt de richting en betrekt je wanneer jouw kennis of akkoord nodig is.</p></div><div className="roles"><article><span>01</span><Bot/><h3>Software voert uit</h3><p>Onderzoekt vragen, prioriteert kansen, maakt voorstellen en volgt zichtbaarheid.</p><small>DOORLOPEND</small></article><article><span>02</span><UserRound/><h3>Adviseur begeleidt</h3><p>Helpt je bedrijfskennis scherp te krijgen, bespreekt prioriteiten en duidt resultaten.</p><small>VAST AANSPREEKPUNT</small></article><article><span>03</span><Check/><h3>Jij beslist</h3><p>Bevestigt wat alleen jij weet en keurt belangrijke contentkeuzes goed.</p><small>OP BESLISMOMENTEN</small></article></div></section>

    <section className="results-section"><div className="results-panel"><div className="results-copy"><p className="overline">Van activiteit naar inzicht</p><h2>Zie wat er gebeurt — zonder schijnzekerheid.</h2><p>Je ziet welk werk is uitgevoerd, wat gepubliceerd kan worden en hoe relevante zoekvragen zich ontwikkelen. Google-verkeer en AI-vermeldingen blijven aparte signalen, ieder met hun eigen context.</p><div className="result-legend"><span><i/> Google-zichtbaarheid</span><span><i/> AI-bronvermeldingen</span></div></div><div className="results-ui"><div className="r-head"><span>VOORBEELDDATA</span><b>Onderwerp: groendak op uitbouw</b></div><div className="r-metrics"><div><small>STATUS CONTENT</small><b>Gepubliceerd</b><span>✓ live gecontroleerd</span></div><div><small>VOLGENDE METING</small><b>Gepland</b><span>Google en AI apart</span></div></div><div className="timeline"><i className="done"/><i className="done"/><i className="current"/><i/><span>Vraag gevonden</span><span>Content live</span><span>Effect volgen</span><span>Bijsturen</span></div></div></div></section>

    <section className="guidance-section"><div className="guidance-visual" aria-hidden="true"><div className="abstract-office"><span className="person one"/><span className="person two"/><span className="table"/><span className="screen">ORBIT<br/><i>••••••</i></span></div></div><div className="guidance-copy"><p className="overline">Menselijke begeleiding</p><h2>Software doet het werk. Je aanspreekpunt houdt overzicht.</h2><p>Je hoeft geen SEO-specialist te worden om gericht aan organische zichtbaarheid te werken. Tijdens vaste contactmomenten krijg je uitleg over keuzes, voortgang en wat er van jou nodig is.</p><div className="guide-list"><span><b>01</b> Bedrijfsinformatie en doelen aanscherpen</span><span><b>02</b> Kansen en prioriteiten bespreken</span><span><b>03</b> Resultaten duiden en vervolgstappen kiezen</span></div></div></section>

    <section className="faq-section"><div><p className="overline">Praktische vragen</p><h2>Goed om vooraf te weten.</h2></div><div className="faq-list"><details><summary>Hoeveel tijd kost dit ons?<span>+</span></summary><p>De software en begeleiding zijn ingericht om bedienwerk te beperken. Jouw inbreng is vooral nodig om unieke bedrijfskennis te bevestigen en belangrijke voorstellen te beoordelen.</p></details><details><summary>Kan ik content eerst goedkeuren?<span>+</span></summary><p>Ja. Belangrijke voorstellen kunnen voor beoordeling worden klaargezet. Automatische publicatie wordt alleen gebruikt waar die koppeling daadwerkelijk beschikbaar en gewenst is.</p></details><details><summary>Werkt ORBIT met onze bestaande website?<span>+</span></summary><p>ORBIT maakt content en publicatiepakketten voor je bestaande website. Welke directe publicatiekoppeling mogelijk is, bespreken we tijdens de kennismaking.</p></details><details><summary>Hoe worden resultaten inzichtelijk?<span>+</span></summary><p>Zoekverkeer, indexatie en zichtbaarheid in AI-antwoorden worden als afzonderlijke signalen gevolgd. Zo blijft duidelijk wat je precies bekijkt.</p></details><details><summary>Wat kost ORBIT ENGINE?<span>+</span></summary><p>De passende aanpak hangt af van je website, ambities en benodigde begeleiding. In de kennismaking brengen we dit eerst in kaart; daarna ontvang je een concreet voorstel.</p></details></div></section>

    <section className="final-section"><span className="orbit-symbol">◒</span><p className="overline">Kennismaken met ORBIT ENGINE</p><h2>Ontdek waar jouw grootste kans ligt.</h2><p>In een vrijblijvende kennismaking bespreken we je bedrijf en doelen, bekijken we waar Google- en AI-zichtbaarheid kan verbeteren en laten we het product zien.</p><a className="primary-button" href={contact}>Plan een kennismaking <ArrowRight/></a><small>Je spreekt rechtstreeks met je vaste aanspreekpunt.</small></section>
  </div>
}
